config/routes.rb
Ritly::Application.routes.draw do
  root "home#index"
        resources :urls, only: [:new, :create, :show]#TODO: restrict this to just :create, :new and :show
        
        get '/:code' => 'urls#redirector'
        get '/:code/preview' => 'urls#preview'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	def new	
		@urls = Url.new
		
	end
	def create
		safe_url_params = params.require(:url).permit(:link)

		@urls = Url.new safe_url_params
		@urls.hash_code = rand(1..1000000)
		@urls.save
		redirect_to @urls
		
	end
	def show
		@urls = Url.find params[:id]
		@full_path = "#{request.protocol}#{request.host_with_port}/#{@urls.hash_code}"

	end
	def redirector
		@urls = Url.find_by hash_code: params[:code]
		if @urls
			redirect_to @urls.link
		else
			redirect_to root_path
		end

	end
	def preview
		@urls = Url.find_by hash_code: params[:code]
		unless @urls
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/_form.html.erb
<%= form_for @urls do |f| %>
<div>
	<%= f.label :url, "Name of movie" %><br>
	<%= f.text_field :url %>
<div>
	<%= f.label :hash_code, "Description" %><br>
	<%= f.text_field :hash_code %>
</div>

<%= f.submit "Submit" %>
<% end %>

app/views/home/index.html.erb
<h2>Welcome to Ritly</h2>
<p><%= link_to "Click here to create a new short link", new_url_path %></p>

app/views/home/new.html.erb
<h1>This should work</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1><a href="<%= root_path %>">Ritly</a></h1>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for @urls do |f| %>
<div>
	<%= f.label :link, "URL" %><br>
	<%= f.text_field :link %>
<div>
	<%= f.label :hash_code, "regenerated URL" %><br>
	<%= f.text_field :hash_code %>
</div>


<% end %>

app/views/urls/index.html.erb
<h1> Ritly </h1>
<p>Welcome to Ritly<p>
	<a href="<%= new_url_path %>">Click here to create a new short link </a>

app/views/urls/new.html.erb
<h2>New Ritly URL</h2>

<br/>

<%= form_for @urls do |f| %>

	<b><%= f.label :link, "URL To Shorten:" %></b>
	<%= f.url_field :link %>
	<br/><br/><br/>
	<% f.submit "Create URL" %>
<% end %>
	
	

		

app/views/urls/preview.html.erb
<h1>Code: <% @urls.hash_code %></h1>
<p>This code will take you to <%= @urls.link %></p>
<%= link_to "Click Here", @urls.link %> to continue

app/views/urls/show.html.erb
<h1><%= @urls.hash_code %> is your code for <%= @urls.link %></h1>
<p> You can direct users to this Ritley URL : <%= link_to @full_path, @full_path %></p>
<p> The Ritly URL will redirect them to: <%= link_to @urls.link, @urls.link %></p>